# static configurations, for env base configs see config/default/application.properties
quarkus:
  swagger-ui:
    path: /swagger-ui.html
    always-include: true
  jaeger:
    enabled: false
    metrics:
      enabled: true
